import type { ComponentCatalogEntry } from './catalog-types.js';

export const visualizationComponentCatalogEntries: readonly ComponentCatalogEntry[] = [
  {
    slug: 'area-chart',
    title: 'Area chart',
    area: 'core',
    group: 'Visualizations',
    status: 'beta',
    intent: 'A responsive normal or stacked area chart for one or more time-series metrics.',
  },
  {
    slug: 'bar-chart',
    title: 'Bar chart',
    area: 'core',
    group: 'Visualizations',
    status: 'beta',
    intent: 'A grouped or stacked bar chart with vertical and horizontal orientations.',
  },
  {
    slug: 'combo-chart',
    title: 'Combo chart',
    area: 'core',
    group: 'Visualizations',
    status: 'beta',
    intent: 'A declared composition of bar and line series with an optional secondary axis.',
  },
  {
    slug: 'bar-list',
    title: 'Bar list',
    area: 'core',
    group: 'Visualizations',
    status: 'beta',
    intent: 'An ordered category list whose native CSS bars compare values against the maximum.',
  },
  {
    slug: 'category-bar',
    title: 'Category bar',
    area: 'core',
    group: 'Visualizations',
    status: 'beta',
    intent: 'A segmented native distribution bar with labels and non-color shape cues.',
  },
  {
    slug: 'donut-chart',
    title: 'Donut chart',
    area: 'core',
    group: 'Visualizations',
    status: 'beta',
    intent: 'A labelled part-to-whole chart with a center label and explicit zero-total state.',
  },
  {
    slug: 'line-chart',
    title: 'Line chart',
    area: 'core',
    group: 'Visualizations',
    status: 'beta',
    intent: 'A responsive multi-series line chart with accessible legend and tooltip behavior.',
  },
  {
    slug: 'progress-circle',
    title: 'Progress circle',
    area: 'core',
    group: 'Visualizations',
    status: 'beta',
    intent: 'A native SVG circular progress indicator for determinate or indeterminate work.',
  },
  {
    slug: 'spark-chart',
    title: 'Spark chart',
    area: 'core',
    group: 'Visualizations',
    status: 'beta',
    intent: 'A compact interactive line, area, or bar chart for dense report surfaces.',
  },
  {
    slug: 'tracker',
    title: 'Tracker',
    area: 'core',
    group: 'Visualizations',
    status: 'beta',
    intent: 'A discrete status sequence whose text and patterns preserve meaning beyond color.',
  },
];
