/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: c8e9b2f07b416b309a1a0e2619a97efb)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	ACCESS_ISSUER: "https://lemn-dev.cloudflareaccess.com";
	DEPLOYMENT_ENVIRONMENT: "production";
	BUILD_VERSION: "0.0.0";
	BUILD_GIT_SHA: "local";
	BUILD_TIME: "local";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ACCESS_ISSUER" | "DEPLOYMENT_ENVIRONMENT" | "BUILD_VERSION" | "BUILD_GIT_SHA" | "BUILD_TIME">> {}
}
