/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: cd1a658047e44f65ffbbe3ccda826049)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	DEPLOYMENT_ENVIRONMENT: "production" | "local";
	BUILD_VERSION: "0.0.0";
	BUILD_GIT_SHA: "local";
	BUILD_TIME: "local";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker/index");
	}
	interface ProductionEnv {
		ASSETS: Fetcher;
		DEPLOYMENT_ENVIRONMENT: "production";
		BUILD_VERSION: "0.0.0";
		BUILD_GIT_SHA: "local";
		BUILD_TIME: "local";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEPLOYMENT_ENVIRONMENT" | "BUILD_VERSION" | "BUILD_GIT_SHA" | "BUILD_TIME">> {}
}
